### PR TITLE
Adds driver for Beckhoff EL3162 analog input

### PR DESCRIPTION
**Pull request by d-loret**
Summary:
Adds the Fastcat wrapper for the JSD driver of Beckhoff El3162
terminal. This is a 2-channel analog input for voltage range 0-10 V.
Inputs have reference ground as common ground potential.

Test Plan:
Performed preliminary testing via a ROS node that communicates with
the terminal. No inputs were connected yet.

Reviewers: alex-brinkman, JosephBowkett

### CODE REVIEW

**Review by alex-brinkman — CHANGES_REQUESTED** [review]
The implementation looks fine to me, once the JSD driver is merged and released we can get this code merged in too.

Can you please add an entry to the `doc/fastcat_device_config_parameters.md`? I know this device does not have any specific voltage range parameters but that is the single-source for device YAML specifications.

**Comment by d-loret** [comment]
@alex-brinkman, I added the entry in the documentation.

**Comment by d-loret** [comment]
@alex-brinkman, do you think we could close this PR and https://github.com/nasa-jpl/fastcat/pull/25 soon?

**Review by alex-brinkman — APPROVED** [review]

**Comment by alex-brinkman** [comment]
Thanks for the nudge, LGTM!

**Pull request merged**
