### PR TITLE
Support gain scheduling in EGD Fastcat driver.

### PR DESCRIPTION
**Pull request by d-loret**
Summary:
Extends the EGD Fastcat driver to enable the selection of the
gain scheduling strategy for its controller and the selection of
particular gain sets when the strategy is manual scheduling.

Test Plan:
Tested on a ROS node that communicates with the Elmo
Gold Drive motor controller.

Reviewers: alex-brinkman, JosephBowkett

### CODE REVIEW

**Comment by d-loret** [comment]
@alex-brinkman, just a reminder that this PR is up for review

**Comment by alex-brinkman** [comment]
LGTM!

**Review by alex-brinkman — APPROVED** [review]

**Comment by d-loret** [comment]
@JosephBowkett, this is now tested and ready for merging.

**Comment by d-loret** [comment]
Forgot this one was already approved. I'm going to merge.

**Pull request merged**
